baseurl = "https://platonicpicnic.club/"
languageCode = "en-us"
title = "The Platonic Picnic Club"
theme = "bootstrap-bp-hugo-startpage"

copyright = "Terra Mauthe"
enableRobotsTXT = true
pygmentsCodeFences = true
canonifyurls = true
paginate = 5

[sitemap]
    changefreq = "weekly"
    priority = 0.5

[permalinks]
    posts = "/:year/:month/:slug/"
    post = "/:year/:month/:slug/"
    pages = "/:slug/"
    page = "/:slug/"

[Author]
  name = "The Platonic Picnic"

[params]
  description = "Text about the site"
  #images = ["logo.jpg"]
  startPageColumns = true
  welcomeText = "Bootstrap-BP hugo startpage"

[[params.searchEngines]]
  name = "Google"
  activated = true
  url = "https://www.google.com/search"

[[params.searchEngines]]
  name = "DuckDuckGo"
  activated = true
  url = "https://duckduckgo.com/"

[[params.searchEngines]]
  name = "Bing"
  activated = true
  url = "https://www.bing.com/search"

[[params.searchEngines]]
  name = "Baidu"
  activated = true
  url = "https://baidu.com/s"
  searchkey = "wd"

[taxonomies]
